const paraPara = document.getElementById("JSp");
const div = document.getElementById("JSdiv");

//Part one of two of this task, under this comment is some of the methods I attempted to get this to work until I got it right.
//const paraPara = document.createTextNode("This paragraph is generated by JavaScript");
//paragraph.innerHTML = "This paragraph is generated by JavaScript";

paraPara.textContent = "This text is changed with JavaScript.";


//Part two of this task:
//const para = document.createElement("p");
const divP = document.createElement("p");
divP.textContent = "This paragraph is generated by JavaScript.";
div.appendChild(divP);  

